name: iOS starter workflow

on:
  push:
    branches:
      - '*'
      - '!develop'
      # - '!main'
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test scheme
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Change to project directory and check
        run: cd flickr/Flickr && ls -lha
        
      - name: Build and run tests
        run: |
          xcodebuild test -scheme FlickrTests -destination 'platform=iOS Simulator,name=iPhone 15'
