name: iOS starter workflow

on:
  push:
    branches:
      - '*'
      - '!develop'
      # - '!main'
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test scheme
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Change to project directory and run tests
        run: |
          cd flickr
          xcodebuild test -scheme FlickrTests -destination 'platform=iOS Simulator,name=Any iOS Simulator Device'
